// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.3";

// src/lib/mcp/tools/list-styles.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z } from "npm:zod@^3.25.76";

// src/data/styles.ts
var BREAD_STYLES = [
  // PIZZA STYLES
  {
    id: "neapolitan",
    name: "Traditionell Napolitansk Pizza",
    description: "Traditionell napolitansk pizza enligt originalrecept",
    category: "pizza",
    region: "Napoli, Italien",
    defaultParams: {
      hydration_pct: 66,
      salt_pct: 2.8,
      sugar_pct: 0,
      oil_pct: 0
    },
    fermentation: {
      bulk_ratio: 0.8,
      // 12-14h bulk, 3h proof
      proof_ratio: 0.2,
      base_yeast_fresh_pct: 0.025,
      // 0.25g per 1000g mjöl
      base_inoculation_pct: 18
    },
    characteristics: ["265g bollar", "L\xE5ng bulkj\xE4sning 12-14h", "21\xB0C j\xE4sning", "Vikning 3 g\xE5nger"],
    flourBlend: [
      { name: "Caputo Pizzeria", percentage: 50, protein_pct: 12.5 },
      { name: "Vigevano Oro di Macina", percentage: 50, protein_pct: 13 }
    ]
  },
  {
    id: "ny_style",
    name: "New York Style Pizza",
    description: "Tunn men seg amerikansk pizza",
    category: "pizza",
    region: "New York, USA",
    defaultParams: {
      hydration_pct: 62,
      salt_pct: 2.2,
      sugar_pct: 1.5,
      oil_pct: 2
    },
    fermentation: {
      bulk_ratio: 0.3,
      proof_ratio: 0.7,
      base_yeast_fresh_pct: 0.2,
      base_inoculation_pct: 20
    },
    characteristics: ["Seg konsistens", "Kan vikas", "Hemugn 250\xB0C", "Mozzarella"]
  },
  {
    id: "detroit",
    name: "Detroit Style Pizza",
    description: "Tjock, luftig siciliansk stil",
    category: "pizza",
    region: "Detroit, USA",
    defaultParams: {
      hydration_pct: 72,
      salt_pct: 2.5,
      sugar_pct: 2,
      oil_pct: 4
    },
    fermentation: {
      bulk_ratio: 0.35,
      proof_ratio: 0.65,
      base_yeast_fresh_pct: 0.25
    },
    characteristics: ["Fyrkantig form", "Knapriga kanter", "Ost till kanterna", "S\xE5s p\xE5 toppen"]
  },
  {
    id: "roman",
    name: "Roman Pizza (Al Taglio)",
    description: "Ultratunn romersk pizza",
    category: "pizza",
    region: "Rom, Italien",
    defaultParams: {
      hydration_pct: 68,
      salt_pct: 2.5,
      sugar_pct: 0,
      oil_pct: 3
    },
    fermentation: {
      bulk_ratio: 0.4,
      proof_ratio: 0.6,
      base_yeast_fresh_pct: 0.08
    },
    characteristics: ["Ultratunn", "Knaprig", "Rektangul\xE4r", "L\xE5ng j\xE4sning"]
  },
  {
    id: "chicago_deep",
    name: "Chicago Deep Dish",
    description: "Djup amerikansk pizza med tjock botten",
    category: "pizza",
    region: "Chicago, USA",
    defaultParams: {
      hydration_pct: 58,
      salt_pct: 2,
      sugar_pct: 1,
      oil_pct: 8
    },
    fermentation: {
      bulk_ratio: 0.5,
      proof_ratio: 0.5,
      base_yeast_fresh_pct: 0.3
    },
    characteristics: ["Djup form", "Sm\xF6rbotten", "Ost p\xE5 botten", "Mycket p\xE5l\xE4gg"]
  },
  // BREAD STYLES
  {
    id: "country_sourdough",
    name: "Country Sourdough",
    description: "Klassiskt lantbr\xF6d med surdeg",
    category: "bread",
    region: "Frankrike",
    defaultParams: {
      hydration_pct: 75,
      salt_pct: 2,
      sugar_pct: 0,
      oil_pct: 0
    },
    fermentation: {
      bulk_ratio: 0.65,
      proof_ratio: 0.35,
      base_yeast_fresh_pct: 0,
      base_inoculation_pct: 20
    },
    characteristics: ["Surdegsj\xE4st", "\xD6ppen krumb", "Syrlig smak", "Tjock skorpa"]
  },
  {
    id: "baguette",
    name: "Baguette Traditionnelle",
    description: "Klassisk fransk baguette med poolish",
    category: "bread",
    region: "Frankrike",
    defaultParams: {
      hydration_pct: 68,
      salt_pct: 2,
      sugar_pct: 0,
      oil_pct: 0,
      preferment: {
        type: "poolish",
        flour_pct: 40,
        hydration_pct: 100
      }
    },
    fermentation: {
      bulk_ratio: 0.6,
      proof_ratio: 0.4,
      base_yeast_fresh_pct: 0.1
    },
    characteristics: ["Poolish f\xF6rj\xE4sning", "Knaprig skorpa", "\xD6ppen krumb", "Traditionell"]
  },
  {
    id: "ciabatta",
    name: "Ciabatta",
    description: "Italienskt br\xF6d med h\xF6g hydrering",
    category: "bread",
    region: "Italien",
    defaultParams: {
      hydration_pct: 80,
      salt_pct: 2.2,
      sugar_pct: 0,
      oil_pct: 1,
      preferment: {
        type: "biga",
        flour_pct: 50,
        hydration_pct: 45
      }
    },
    fermentation: {
      bulk_ratio: 0.7,
      proof_ratio: 0.3,
      base_yeast_fresh_pct: 0.08
    },
    characteristics: ["Biga f\xF6rj\xE4sning", "Mycket luftig", "Oregelbundna h\xE5l", "Mjuk skorpa"]
  },
  {
    id: "focaccia",
    name: "Focaccia Genovese",
    description: "Italiensk platt olivoljebr\xF6d",
    category: "bread",
    region: "Genua, Italien",
    defaultParams: {
      hydration_pct: 70,
      salt_pct: 2.5,
      sugar_pct: 0,
      oil_pct: 8
    },
    fermentation: {
      bulk_ratio: 0.4,
      proof_ratio: 0.6,
      base_yeast_fresh_pct: 0.15
    },
    characteristics: ["Olivolja", "Platt form", "Mjuk konsistens", "Toppings"]
  },
  {
    id: "pain_de_mie",
    name: "Pain de Mie",
    description: "Franskt formbr\xF6d (sandwich bread)",
    category: "bread",
    region: "Frankrike",
    defaultParams: {
      hydration_pct: 65,
      salt_pct: 1.8,
      sugar_pct: 3,
      oil_pct: 4
    },
    fermentation: {
      bulk_ratio: 0.45,
      proof_ratio: 0.55,
      base_yeast_fresh_pct: 0.25
    },
    characteristics: ["Mjuk skorpa", "Fin krumb", "Kvadratisk form", "Sandwich"]
  },
  // PREFERMENT BREADS
  {
    id: "poolish_bread",
    name: "Poolish Country Bread",
    description: "Rustikt br\xF6d med poolish f\xF6rj\xE4sning",
    category: "preferment",
    region: "Frankrike",
    defaultParams: {
      hydration_pct: 72,
      salt_pct: 2,
      sugar_pct: 0,
      oil_pct: 0,
      preferment: {
        type: "poolish",
        flour_pct: 50,
        hydration_pct: 100
      }
    },
    fermentation: {
      bulk_ratio: 0.6,
      proof_ratio: 0.4,
      base_yeast_fresh_pct: 0.08
    },
    characteristics: ["Poolish 12-16h", "Komplex smak", "\xD6ppen krumb", "Knaprig skorpa"],
    flourBlend: [
      { name: "Br\xF6d\xADmj\xF6l", percentage: 80, protein_pct: 12.5 },
      { name: "Fullkornsvete", percentage: 20, protein_pct: 14 }
    ]
  },
  {
    id: "biga_pane",
    name: "Pane Pugliese (Biga)",
    description: "Italienskt br\xF6d med biga f\xF6rj\xE4sning",
    category: "preferment",
    region: "Apulien, Italien",
    defaultParams: {
      hydration_pct: 70,
      salt_pct: 2.2,
      sugar_pct: 0,
      oil_pct: 0,
      preferment: {
        type: "biga",
        flour_pct: 60,
        hydration_pct: 45
      }
    },
    fermentation: {
      bulk_ratio: 0.65,
      proof_ratio: 0.35,
      base_yeast_fresh_pct: 0.06
    },
    characteristics: ["Biga 12-24h", "N\xF6taktig smak", "Fin krumb", "H\xE5llbart"],
    flourBlend: [
      { name: "Tipo 0", percentage: 70, protein_pct: 11.5 },
      { name: "Tipo 1", percentage: 30, protein_pct: 12 }
    ]
  },
  {
    id: "pizza_poolish",
    name: "Neapolitan Poolish Pizza",
    description: "Napolitansk pizza med poolish enligt traditionellt recept",
    category: "pizza",
    region: "Napoli, Italien",
    defaultParams: {
      hydration_pct: 60,
      // 300g vatten / 500g mjöl
      salt_pct: 2.4,
      // 12g salt / 500g mjöl
      sugar_pct: 0.6,
      // 3g honung / 500g mjöl
      oil_pct: 0,
      preferment: {
        type: "poolish",
        flour_pct: 35,
        // 175g / 500g total mjöl
        hydration_pct: 100
        // 175g vatten i poolish
      }
    },
    fermentation: {
      bulk_ratio: 0.15,
      // 2h rumstemperatur efter blandning
      proof_ratio: 0.85,
      // 18-24h kall + 2h uppvärmning
      base_yeast_fresh_pct: 0.3
      // Motsvarar 1g IDY i poolish
    },
    characteristics: ["270g bollar", "Poolish 18-24h kall", "2h uppv\xE4rmning", "Leopard spotting"],
    flourBlend: [
      { name: "Tipo 00", percentage: 100, protein_pct: 12.5 }
    ]
  },
  {
    id: "pizza_biga",
    name: "Pizza Napoletana (100% Biga)",
    description: "Napolitansk pizza med 100% biga",
    category: "pizza",
    region: "Napoli, Italien",
    defaultParams: {
      hydration_pct: 70,
      // 450-500ml + 200-250ml = 650-750ml / 1000g
      salt_pct: 2.8,
      // 28g / 1000g mjöl
      sugar_pct: 1,
      // 10g malt / 1000g mjöl
      oil_pct: 0,
      preferment: {
        type: "biga",
        flour_pct: 100,
        // 100% biga - inget extra mjöl
        hydration_pct: 47
        // 450-500ml / 1000g mjöl i bigan
      }
    },
    fermentation: {
      bulk_ratio: 0.2,
      // 30min vila efter knådning
      proof_ratio: 0.8,
      // 18h biga + 3h bollning
      base_yeast_fresh_pct: 0.25
      // 2-3g / 1000g mjöl
    },
    characteristics: ["260-280g bollar", "100% biga", "18h kallf\xF6rj\xE4sning", "W300+ mj\xF6l kr\xE4vs"],
    flourBlend: [
      { name: "Molino Pizzuti Costa d'Amalfi", percentage: 60, protein_pct: 13 },
      { name: "Vigevano Tramonti Oro", percentage: 40, protein_pct: 14 }
    ]
  },
  {
    id: "sicilian_pizza",
    name: "Sicilian Pizza",
    description: "Tjock siciliansk pizza (Sfincione)",
    category: "pizza",
    region: "Sicilien, Italien",
    defaultParams: {
      hydration_pct: 68,
      salt_pct: 2.8,
      sugar_pct: 1,
      oil_pct: 6
    },
    fermentation: {
      bulk_ratio: 0.4,
      proof_ratio: 0.6,
      base_yeast_fresh_pct: 0.15,
      base_inoculation_pct: 22
    },
    characteristics: ["Tjock botten", "Olivolja", "L\xF6ktoppning", "Breadcrumbs"],
    flourBlend: [
      { name: "Tipo 00", percentage: 60, protein_pct: 11 },
      { name: "Semolina", percentage: 40, protein_pct: 13.5 }
    ]
  },
  // ENRICHED BREADS
  {
    id: "milkbread",
    name: "Milkbread (Hokkaido)",
    description: "Japanskt mj\xF6lkbr\xF6d - magiskt mjukt och luftigt",
    category: "enriched",
    region: "Japan/Sverige",
    defaultParams: {
      hydration_pct: 64,
      // 345g vatten / 540g mjöl
      salt_pct: 1.1,
      // 1 tsk salt ≈ 6g / 540g mjöl
      sugar_pct: 6.5,
      // 35g strösocker / 540g mjöl
      oil_pct: 5.6
      // 30g smör / 540g mjöl
    },
    fermentation: {
      bulk_ratio: 0.6,
      proof_ratio: 0.4,
      base_yeast_fresh_pct: 2.8
      // 15g jäst / 540g mjöl
    },
    characteristics: ["Torrmj\xF6lkspulver 4.6%", "Extremt mjuk", "L\xE5ng h\xE5llbarhet", "Tangzhong-metod"],
    flourBlend: [
      { name: "\xD6landsvetemj\xF6l (eller br\xF6d\xADmj\xF6l)", percentage: 100, protein_pct: 11.5 }
    ]
  },
  {
    id: "pain_de_mie_traditional",
    name: "Pain de Mie (Traditionell)",
    description: "Klassiskt franskt formbr\xF6d enligt originalrecept",
    category: "enriched",
    region: "Frankrike",
    defaultParams: {
      hydration_pct: 69,
      // (250g vatten + 250g mjölk) / 720g mjöl
      salt_pct: 2.1,
      // 15g salt / 720g mjöl
      sugar_pct: 2.6,
      // 19g honung / 720g mjöl
      oil_pct: 14
      // 100g smör / 720g mjöl
    },
    fermentation: {
      bulk_ratio: 0.4,
      proof_ratio: 0.6,
      base_yeast_fresh_pct: 2
      // 6g torrjäst motsvarar ~15g färsk
    },
    characteristics: ["Mj\xF6lk + vatten", "Honung ist\xE4llet f\xF6r socker", "Mycket sm\xF6r", "Kvadratisk form"],
    flourBlend: [
      { name: "Vetemj\xF6l", percentage: 100, protein_pct: 11.5 }
    ]
  },
  {
    id: "sourdough_form_bread",
    name: "Surdeg Formbr\xF6d",
    description: "Svenskt surdegsbr\xF6d f\xF6r form - Martin Johanssons recept",
    category: "bread",
    region: "Sverige",
    defaultParams: {
      hydration_pct: 62.5,
      // 250g vatten / 400g mjöl
      salt_pct: 2.4,
      // Uppskattad 1½ tsk ≈ 9.6g / 400g
      sugar_pct: 0,
      oil_pct: 0
    },
    fermentation: {
      bulk_ratio: 0.7,
      proof_ratio: 0.3,
      base_yeast_fresh_pct: 0,
      base_inoculation_pct: 50
      // 200g surdeg / 400g mjöl
    },
    characteristics: ["50% surdegsinokulation", "Vikning i bunke", "Avl\xE5ng limpa", "3-4h j\xE4sning"],
    flourBlend: [
      { name: "Vetemj\xF6l Special", percentage: 100, protein_pct: 12 }
    ]
  },
  {
    id: "sourdough_tortillas",
    name: "Surdeg Tortillas",
    description: "Mexikanska tortillas med svensk surdeg",
    category: "bread",
    region: "Mexico/Sverige",
    defaultParams: {
      hydration_pct: 57,
      // (150ml surdeg/2 + 250ml vatten) / 420g mjöl
      salt_pct: 2.3,
      // 1½ tsk ≈ 9.6g / 420g mjöl
      sugar_pct: 0,
      oil_pct: 24
      // 100g smält smör / 420g mjöl
    },
    fermentation: {
      bulk_ratio: 0.2,
      proof_ratio: 0.8,
      base_yeast_fresh_pct: 0,
      base_inoculation_pct: 18
      // 150ml surdeg ≈ 75g / 420g mjöl
    },
    characteristics: ["MMS-metoden", "Hett vatten", "Sm\xE4lt sm\xF6r", "12 stora eller 24 sm\xE5"],
    flourBlend: [
      { name: "Vetemj\xF6l", percentage: 100, protein_pct: 11 }
    ]
  },
  {
    id: "brioche",
    name: "Brioche",
    description: "Rikt franskt sm\xF6rbr\xF6d",
    category: "enriched",
    region: "Frankrike",
    defaultParams: {
      hydration_pct: 58,
      salt_pct: 1.8,
      sugar_pct: 12,
      oil_pct: 40
      // Smör
    },
    fermentation: {
      bulk_ratio: 0.5,
      proof_ratio: 0.5,
      base_yeast_fresh_pct: 1.2
    },
    characteristics: ["Mycket sm\xF6r", "S\xF6t", "Mjuk konsistens", "\xC4ggrik"]
  },
  {
    id: "challah",
    name: "Challah",
    description: "Judiskt fl\xE4tat \xE4ggbr\xF6d",
    category: "enriched",
    region: "\xD6steuropa",
    defaultParams: {
      hydration_pct: 55,
      salt_pct: 1.5,
      sugar_pct: 8,
      oil_pct: 8
    },
    fermentation: {
      bulk_ratio: 0.45,
      proof_ratio: 0.55,
      base_yeast_fresh_pct: 0.8
    },
    characteristics: ["\xC4ggrik", "Fl\xE4tat", "S\xF6t", "Glansig yta"]
  },
  {
    id: "pita",
    name: "Pita Bread",
    description: "Mellan\xF6stern fickbr\xF6d",
    category: "bread",
    region: "Mellan\xF6stern",
    defaultParams: {
      hydration_pct: 62,
      salt_pct: 2,
      sugar_pct: 1,
      oil_pct: 2
    },
    fermentation: {
      bulk_ratio: 0.5,
      proof_ratio: 0.5,
      base_yeast_fresh_pct: 0.5
    },
    characteristics: ["Platt", "Ficka", "Snabb bakning", "Mjuk"]
  },
  {
    id: "sourdough_rye",
    name: "Swedish Rye Sourdough",
    description: "Svenskt r\xE5gsurdegsbr\xF6d",
    category: "bread",
    region: "Sverige",
    defaultParams: {
      hydration_pct: 72,
      salt_pct: 2.2,
      sugar_pct: 0,
      oil_pct: 0
    },
    fermentation: {
      bulk_ratio: 0.7,
      proof_ratio: 0.3,
      base_yeast_fresh_pct: 0,
      base_inoculation_pct: 25
    },
    characteristics: ["R\xE5gsurdeg", "M\xF6rk f\xE4rg", "T\xE4t krumb", "Syrlig"],
    flourBlend: [
      { name: "R\xE5gmj\xF6l", percentage: 30, protein_pct: 8 },
      { name: "Vetemj\xF6l", percentage: 70, protein_pct: 11.5 }
    ]
  },
  {
    id: "multigrain_sourdough",
    name: "Multigrain Sourdough",
    description: "Flerkornsbr\xF6d med surdeg",
    category: "bread",
    region: "Norden",
    defaultParams: {
      hydration_pct: 78,
      salt_pct: 2,
      sugar_pct: 0,
      oil_pct: 2
    },
    fermentation: {
      bulk_ratio: 0.65,
      proof_ratio: 0.35,
      base_yeast_fresh_pct: 0,
      base_inoculation_pct: 22
    },
    characteristics: ["Flera kornsorter", "N\xF6taktig", "H\xF6g fiber", "M\xE4ttande"],
    flourBlend: [
      { name: "Br\xF6d\xADmj\xF6l", percentage: 50, protein_pct: 12.5 },
      { name: "R\xE5g\xADmj\xF6l", percentage: 20, protein_pct: 8 },
      { name: "Speltvete", percentage: 30, protein_pct: 14 }
    ]
  }
];
var getStyleById = (id) => {
  return BREAD_STYLES.find((style) => style.id === id);
};

// src/lib/mcp/tools/list-styles.ts
var list_styles_default = defineTool({
  name: "list_styles",
  title: "List dough styles",
  description: "List all built-in bread and pizza styles with their id, name, region and category. Optionally filter by category.",
  inputSchema: {
    category: z.enum(["pizza", "bread", "enriched", "preferment"]).optional().describe("Optional category filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const styles = BREAD_STYLES.filter((s) => !category || s.category === category).map((s) => ({
      id: s.id,
      name: s.name,
      category: s.category,
      region: s.region,
      description: s.description
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(styles, null, 2) }],
      structuredContent: { styles }
    };
  }
});

// src/lib/mcp/tools/get-style.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z2 } from "npm:zod@^3.25.76";
var get_style_default = defineTool2({
  name: "get_style",
  title: "Get dough style details",
  description: "Get the full definition of one style: default hydration, salt, sugar, oil, preferment, fermentation ratios, flour blend and characteristics.",
  inputSchema: {
    style_id: z2.string().min(1).describe("Style id, e.g. 'neapolitan' (see list_styles).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ style_id }) => {
    const style = getStyleById(style_id);
    if (!style) throw new ToolError(`Unknown style id: ${style_id}. Use list_styles to see valid ids.`);
    return {
      content: [{ type: "text", text: JSON.stringify(style, null, 2) }],
      structuredContent: { style }
    };
  }
});

// src/lib/mcp/tools/calculate-recipe.ts
import { defineTool as defineTool3, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z3 } from "npm:zod@^3.25.76";

// src/core/calculations.ts
var YEAST_CONVERSIONS = {
  fresh_to_ady: 0.4,
  fresh_to_idy: 0.33,
  ady_to_idy: 0.82
};
function getTemperatureFactor(temp, refTemp = 23, q10 = 2.2) {
  return Math.pow(q10, (temp - refTemp) / 10);
}
var REFERENCE_LEVAIN_TIME = 6;
var INOCULATION_MIN = 3;
var INOCULATION_MAX = 25;
function computeRoomEquivTime(totalTime, coldHours = 0) {
  const coldRetardFactor = 0.3;
  const effectiveColdHours = Math.min(Math.max(coldHours, 0), totalTime);
  return Math.max(0.5, totalTime - effectiveColdHours + effectiveColdHours * coldRetardFactor);
}
function computeInoculationPct(baseInoculation, roomEquivTime, roomTemp, leavenType = "sourdough") {
  if (leavenType === "commercial") return 0;
  const tempFactor = getTemperatureFactor(roomTemp);
  const scaled = baseInoculation * (REFERENCE_LEVAIN_TIME / roomEquivTime) / tempFactor;
  let pct = Math.min(Math.max(scaled, INOCULATION_MIN), INOCULATION_MAX);
  if (leavenType === "hybrid") pct *= 0.5;
  return Math.round(pct * 10) / 10;
}
function calculateRecipe(inputs) {
  const { style, ballWeight, ballCount, totalTime, roomTemp, leavenType, yeastForm, mixing, desiredDoughTemp, coldTemp = 4, coldHours = 0 } = inputs;
  const hydrationPct = inputs.hydration ?? style.defaultParams.hydration_pct;
  const saltPct = inputs.salt ?? style.defaultParams.salt_pct;
  const sugarPct = inputs.sugar ?? style.defaultParams.sugar_pct;
  const oilPct = inputs.oil ?? style.defaultParams.oil_pct;
  const totalDoughWeight = Math.max(0, ballWeight * ballCount);
  const extrasPct = style.id === "milkbread" ? 4.6 : 0;
  const totalPercentage = 100 + hydrationPct + saltPct + sugarPct + oilPct + extrasPct;
  const totalFlour = totalDoughWeight / (totalPercentage / 100);
  const effectiveColdHours = Math.min(Math.max(coldHours, 0), totalTime);
  const roomEquivTime = computeRoomEquivTime(totalTime, effectiveColdHours);
  let yeastPercentage = 0;
  if (leavenType === "commercial" || leavenType === "hybrid") {
    const baseFreshYeast = style.fermentation.base_yeast_fresh_pct || 0.3;
    const tempFactor = getTemperatureFactor(roomTemp);
    const timeFactor = 24 / roomEquivTime;
    const clamp = (v, lo, hi) => Math.min(Math.max(v, lo), hi);
    const saltCorrection = clamp(1 + 0.05 * (saltPct - 2), 0.8, 1.4);
    const sugarCorrection = clamp(1 + 0.02 * sugarPct, 0.8, 1.5);
    const hydrationCorrection = clamp(1 - 5e-3 * (hydrationPct - 62), 0.7, 1.3);
    let freshYeastPct = baseFreshYeast * timeFactor / tempFactor * saltCorrection * sugarCorrection * hydrationCorrection;
    if (leavenType === "hybrid") freshYeastPct *= 0.5;
    if (yeastForm === "active_dry") {
      yeastPercentage = freshYeastPct * YEAST_CONVERSIONS.fresh_to_ady;
    } else if (yeastForm === "instant") {
      yeastPercentage = freshYeastPct * YEAST_CONVERSIONS.fresh_to_idy;
    } else {
      yeastPercentage = freshYeastPct;
    }
  }
  const usesStarter = leavenType === "sourdough" || leavenType === "hybrid";
  const baseInoculation = style.fermentation.base_inoculation_pct ?? 20;
  const inoculationPct = usesStarter ? computeInoculationPct(baseInoculation, roomEquivTime, roomTemp, leavenType) : 0;
  const ingredients = [];
  if (style.flourBlend && style.flourBlend.length > 0) {
    style.flourBlend.forEach((flour) => {
      ingredients.push({
        name: flour.name,
        grams: Math.round(totalFlour * (flour.percentage / 100) * 10) / 10,
        percentage: flour.percentage,
        type: "flour"
      });
    });
  } else {
    ingredients.push({
      name: "Mj\xF6l (Tipo 00/Vetemj\xF6l)",
      grams: Math.round(totalFlour * 10) / 10,
      percentage: 100,
      type: "flour"
    });
  }
  ingredients.push({
    name: "Vatten",
    grams: Math.round(totalFlour * (hydrationPct / 100) * 10) / 10,
    percentage: hydrationPct,
    type: "water"
  });
  ingredients.push({
    name: "Salt",
    grams: Math.round(totalFlour * (saltPct / 100) * 10) / 10,
    percentage: saltPct,
    type: "salt"
  });
  if (yeastPercentage > 0) {
    const yeastNames = {
      fresh: "F\xE4rsk j\xE4st",
      active_dry: "Torrj\xE4st (aktiv)",
      instant: "Torrj\xE4st (instant)"
    };
    ingredients.push({
      name: yeastNames[yeastForm],
      grams: Math.round(totalFlour * (yeastPercentage / 100) * 100) / 100,
      percentage: Math.round(yeastPercentage * 100) / 100,
      type: "yeast"
    });
  }
  if (usesStarter && inoculationPct > 0) {
    const starterFlour = totalFlour * (inoculationPct / 100);
    const starterWater = starterFlour;
    const totalStarter = starterFlour + starterWater;
    ingredients.push({
      name: "Surdeg (100% hydrering)",
      grams: Math.round(totalStarter * 10) / 10,
      percentage: Math.round(inoculationPct * 2 * 10) / 10,
      // flour + water
      type: "starter"
    });
    const firstFlourIndex = ingredients.findIndex((ing) => ing.type === "flour");
    const waterIndex = ingredients.findIndex((ing) => ing.type === "water");
    if (firstFlourIndex !== -1) {
      ingredients[firstFlourIndex].grams = Math.round(Math.max(0, ingredients[firstFlourIndex].grams - starterFlour) * 10) / 10;
      ingredients[firstFlourIndex].name += " (ut\xF6ver surdegen)";
    }
    if (waterIndex !== -1) {
      ingredients[waterIndex].grams = Math.round(Math.max(0, ingredients[waterIndex].grams - starterWater) * 10) / 10;
      ingredients[waterIndex].name += " (ut\xF6ver surdegen)";
    }
  }
  if (sugarPct > 0) {
    const sugarName = style.id === "pain_de_mie_traditional" ? "Honung" : style.id === "milkbread" ? "Str\xF6socker" : "Socker";
    ingredients.push({
      name: sugarName,
      grams: Math.round(totalFlour * (sugarPct / 100) * 10) / 10,
      percentage: sugarPct,
      type: "sugar"
    });
  }
  if (style.id === "milkbread") {
    ingredients.push({
      name: "Torrmj\xF6lkspulver",
      grams: Math.round(totalFlour * 0.046 * 10) / 10,
      percentage: 4.6,
      type: "flour"
      // Treat as flour for calculation purposes
    });
  }
  if (style.id === "pain_de_mie_traditional") {
    const waterIndex = ingredients.findIndex((ing) => ing.type === "water");
    if (waterIndex !== -1) {
      const totalLiquid = ingredients[waterIndex].grams;
      const waterAmount = totalLiquid / 2;
      const milkAmount = totalLiquid / 2;
      ingredients[waterIndex].grams = Math.round(waterAmount * 10) / 10;
      ingredients[waterIndex].name = "Fingervarmt vatten";
      ingredients[waterIndex].percentage = Math.round(waterAmount / totalFlour * 1e3) / 10;
      ingredients.push({
        name: "Standardmj\xF6lk",
        grams: Math.round(milkAmount * 10) / 10,
        percentage: Math.round(milkAmount / totalFlour * 1e3) / 10,
        type: "water"
      });
    }
  }
  if (style.id === "sourdough_tortillas") {
    const waterIndex = ingredients.findIndex((ing) => ing.type === "water");
    if (waterIndex !== -1) {
      ingredients[waterIndex].name = "Hett vatten";
    }
  }
  if (oilPct > 0) {
    const oilName = style.id === "brioche" ? "Sm\xF6r" : style.id === "focaccia" ? "Olivolja" : style.id === "milkbread" ? "Sm\xF6r" : style.id === "pain_de_mie_traditional" ? "Sm\xF6r" : style.id === "sourdough_tortillas" ? "Sm\xE4lt sm\xF6r" : "Olja";
    ingredients.push({
      name: oilName,
      grams: Math.round(totalFlour * (oilPct / 100) * 10) / 10,
      percentage: oilPct,
      type: "oil"
    });
  }
  const frictionFactors = { hand: 2, spiral: 8, planetary: 6, dlx: 4 };
  const frictionFactor = frictionFactors[mixing];
  const flourTemp = roomTemp;
  const rawWaterTemp = desiredDoughTemp * 3 - flourTemp - roomTemp - frictionFactor;
  const waterTemp = Math.min(Math.max(rawWaterTemp, 1), 55);
  const ratioSum = style.fermentation.bulk_ratio + style.fermentation.proof_ratio || 1;
  const bulkTime = totalTime * (style.fermentation.bulk_ratio / ratioSum);
  const proofTime = totalTime * (style.fermentation.proof_ratio / ratioSum);
  ingredients.forEach((ing) => {
    const pct = totalFlour > 0 ? ing.grams / totalFlour * 100 : 0;
    ing.percentage = ing.type === "yeast" ? Math.round(pct * 1e3) / 1e3 : Math.round(pct * 10) / 10;
  });
  const timeline = generateTimeline(bulkTime, proofTime, mixing, style);
  const notes = generateNotes(inputs, yeastPercentage, waterTemp, {
    hydrationPct,
    oilPct,
    rawWaterTemp,
    coldHours: effectiveColdHours
  });
  if (usesStarter && inoculationPct > 0) {
    notes.push(
      `\u2139\uFE0F Procenten visar varje ingrediens andel av det totala mj\xF6let (${Math.round(totalFlour)}g), d\xE4r surdegens mj\xF6l (${Math.round(totalFlour * (inoculationPct / 100))}g) och vatten redan \xE4r avr\xE4knade fr\xE5n mj\xF6l- och vattenposten. Total hydrering blir ${hydrationPct}%.`
    );
    notes.push(
      `\u{1FAD9} Surdegsratio: ${inoculationPct}% av mj\xF6lvikten kommer fr\xE5n surdegen, dvs ${Math.round(inoculationPct * 2 * 10) / 10}% f\xE4rdig surdeg (100% hydrering) p\xE5 mj\xF6let. Basen \xE4r ${baseInoculation}% vid 23\xB0C och ~6h j\xE4sning \u2013 m\xE4ngden skalas ned vid l\xE4ngre tid eller varmare rum och begr\xE4nsas till 3\u201325%.`
    );
    notes.push(
      "\u{1FAD9} Anv\xE4nd mogen surdeg: mata 1:5:5 och anv\xE4nd den p\xE5 toppen (ca 4\u20136h vid 23\xB0C). Tr\xF6g eller nymatad surdeg = l\xE4ngre j\xE4sning \xE4n ber\xE4knat."
    );
  }
  return {
    ingredients,
    waterTemp: Math.round(waterTemp * 10) / 10,
    bulkTime: Math.round(bulkTime * 10) / 10,
    proofTime: Math.round(proofTime * 10) / 10,
    totalFlour: Math.round(totalFlour),
    yeastPercentage: Math.round(yeastPercentage * 1e3) / 1e3,
    timeline,
    notes,
    params: {
      hydration: hydrationPct,
      salt: saltPct,
      sugar: sugarPct,
      oil: oilPct,
      roomEquivTime: Math.round(roomEquivTime * 10) / 10,
      coldHours: effectiveColdHours,
      totalTime,
      totalDoughWeight,
      inoculationPct,
      baseInoculationPct: baseInoculation,
      leavenType,
      roomTemp
    }
  };
}
function generateTimeline(bulkTime, proofTime, mixing, style) {
  const timeline = [];
  switch (style.id) {
    case "neapolitan":
      return generateNeapolitanTimeline(bulkTime, proofTime);
    case "pizza_poolish":
      return generatePoolishTimeline(bulkTime, proofTime);
    case "pizza_biga":
      return generateBigaTimeline(bulkTime, proofTime);
    case "milkbread":
      return generateMilkbreadTimeline(bulkTime, proofTime);
    case "pain_de_mie_traditional":
      return generatePainDeMieTimeline(bulkTime, proofTime);
    case "sourdough_form_bread":
      return generateSourdoughFormTimeline(bulkTime, proofTime);
    case "sourdough_tortillas":
      return generateTortillaTimeline(bulkTime, proofTime);
    case "country_sourdough":
      return generateCountrySourdoughTimeline(bulkTime, proofTime);
    case "baguette":
      return generateBaguetteTimeline(bulkTime, proofTime);
    default:
      return generateGenericTimeline(bulkTime, proofTime, mixing, style);
  }
}
function generateNeapolitanTimeline(bulkTime, proofTime) {
  return [
    {
      time: "00:00",
      action: "Blanda vatten, salt och j\xE4st",
      description: "15\xB0C vatten, 28-30g salt, 0.25g f\xE4rsk j\xE4st - r\xF6r tills uppl\xF6st"
    },
    {
      time: "00:05",
      action: "Tills\xE4tt mj\xF6l",
      description: "H\xE4ll i 1000g mj\xF6l (Caputo Pizzeria + Vigevano), blanda snabbt f\xF6r hand"
    },
    {
      time: "00:30",
      action: "F\xF6rsta vikningen",
      description: "Vik degen 4-5 g\xE5nger tills sp\xE4nd och sl\xE4t, vila 15 min"
    },
    {
      time: "00:45",
      action: "Andra vikningen",
      description: "Upprepa vikning, vila 15 min"
    },
    {
      time: "01:00",
      action: "Tredje vikningen",
      description: "Sista vikning, ta ut 80g f\xF6r j\xE4sningskontroll"
    },
    {
      time: formatTime(bulkTime),
      action: "Dela och bolla",
      description: "Dela till 265g bollar, bolla med sp\xE4nning"
    },
    {
      time: formatTime(bulkTime + proofTime),
      action: "Klart f\xF6r utbakning",
      description: "Kontrollera j\xE4sning (25-29 p\xE5 regnm\xE4tare), kavla f\xF6rsiktigt"
    }
  ];
}
function generatePoolishTimeline(bulkTime, proofTime) {
  return [
    {
      time: "DAG 1 - 00:00",
      action: "G\xF6r poolish",
      description: "175g mj\xF6l + 175g ljummet vatten + 3g honung + 1g torrj\xE4st"
    },
    {
      time: "DAG 1 - 02:00",
      action: "Poolish i kyl",
      description: "Poolish till kylsk\xE5p i 18-24h"
    },
    {
      time: "DAG 2 - 00:00",
      action: "Poolish till rumstemperatur",
      description: "Ta ut poolish 1h f\xF6re anv\xE4ndning"
    },
    {
      time: "DAG 2 - 01:00",
      action: "Blanda slutdeg",
      description: "Poolish + 125g vatten + 325g mj\xF6l + 12g salt, kn\xE5da 5-8 min"
    },
    {
      time: `DAG 2 - ${formatTime(1 + bulkTime)}`,
      action: "Dela och bolla",
      description: "Dela till 270g bollar, vila 20 min"
    },
    {
      time: `DAG 2 - ${formatTime(1 + bulkTime + proofTime)}`,
      action: "Klart f\xF6r utbakning",
      description: "Degen ska vara luftig och l\xE4tt att str\xE4cka"
    }
  ];
}
function generateBigaTimeline(bulkTime, proofTime) {
  return [
    {
      time: "DAG 1 - 00:00",
      action: "G\xF6r biga",
      description: "1000g mj\xF6l + 450-500ml vatten + 2-3g j\xE4st, blanda till j\xE4mn deg"
    },
    {
      time: "DAG 1 - 18:00",
      action: "Biga f\xE4rdig",
      description: "Biga klar efter 18h vid 16\xB0C, ska lukta tydligt"
    },
    {
      time: "DAG 2 - 00:00",
      action: "Kn\xE5da slutdeg",
      description: "Biga + 200-250ml isvatten + 28g salt + 10g malt"
    },
    {
      time: "DAG 2 - 00:30",
      action: "Windowpane-test",
      description: "Degen ska klara windowpane-test och k\xE4nnas tuggumiaktig"
    },
    {
      time: `DAG 2 - ${formatTime(0.5 + bulkTime)}`,
      action: "Dela och bolla",
      description: "Dela till 260-280g bollar f\xF6r 36cm pizzor"
    },
    {
      time: `DAG 2 - ${formatTime(0.5 + bulkTime + proofTime)}`,
      action: "Klart f\xF6r utbakning",
      description: "Degbollar redo efter 3h vid rumstemperatur"
    }
  ];
}
function generateMilkbreadTimeline(bulkTime, proofTime) {
  return [
    {
      time: "00:00",
      action: "G\xF6r tangzhong",
      description: "Koka 30g mj\xF6l + 150ml mj\xF6lk/vatten till tjock konsistens, kyl"
    },
    {
      time: "00:30",
      action: "Blanda deg",
      description: "Mj\xF6l, socker, salt, torrj\xE4st, tangzhong, mj\xF6lk - kn\xE5da 8 min"
    },
    {
      time: "00:38",
      action: "Tills\xE4tt sm\xF6r",
      description: "Rumstempererat sm\xF6r portionsvis, kn\xE5da till sl\xE4tt"
    },
    {
      time: formatTime(bulkTime),
      action: "Forma br\xF6d",
      description: "Dela degen, forma och l\xE4gg i sm\xF6rd form"
    },
    {
      time: formatTime(bulkTime + proofTime),
      action: "Pensla och gr\xE4dda",
      description: "Pensla med mj\xF6lk, gr\xE4dda 180\xB0C i 30-35 min"
    }
  ];
}
function generatePainDeMieTimeline(bulkTime, proofTime) {
  return [
    {
      time: "00:00",
      action: "L\xF6s j\xE4st i mj\xF6lk",
      description: "Blanda j\xE4st i fingervarmt mj\xF6lk/vatten (50/50)"
    },
    {
      time: "00:05",
      action: "Tills\xE4tt mj\xF6l och honung",
      description: "Blanda mj\xF6l, honung och j\xE4stblandning"
    },
    {
      time: "00:15",
      action: "Kn\xE5da med sm\xF6r",
      description: "Kn\xE5da 10-15 min till sl\xE4t deg med sm\xF6r"
    },
    {
      time: formatTime(bulkTime),
      action: "Forma och l\xE4gg i form",
      description: "Forma till limpa, l\xE4gg i sm\xF6rd form med lock"
    },
    {
      time: formatTime(bulkTime + proofTime),
      action: "Gr\xE4dda",
      description: "Gr\xE4dda 220\xB0C till dubbel storlek, s\xE4nk till 190\xB0C"
    }
  ];
}
function generateSourdoughFormTimeline(bulkTime, proofTime) {
  return [
    {
      time: "00:00",
      action: "Autolys",
      description: "Blanda mj\xF6l och vatten, vila 30 min"
    },
    {
      time: "00:30",
      action: "Tills\xE4tt surdeg och salt",
      description: "Arbeta in aktiv surdeg och salt f\xF6rsiktigt"
    },
    {
      time: "01:00",
      action: "F\xF6rsta vikningen",
      description: "Vikning i bunke, vila 30 min"
    },
    {
      time: "01:30",
      action: "Andra vikningen",
      description: "Upprepa vikning, vila 30 min"
    },
    {
      time: "02:00",
      action: "Tredje vikningen",
      description: "Sista vikning i bunke"
    },
    {
      time: formatTime(bulkTime),
      action: "Forma till limpa",
      description: "Forma till avl\xE5ng limpa, l\xE4gg i korg"
    },
    {
      time: formatTime(bulkTime + proofTime),
      action: "Gr\xE4dda",
      description: "Gr\xE4dda med \xE5nga 230\xB0C i 20 min, sedan 200\xB0C"
    }
  ];
}
function generateTortillaTimeline(bulkTime, proofTime) {
  return [
    {
      time: "00:00",
      action: "MMS-metod: Het v\xE4tska",
      description: "Blanda hett vatten (80\xB0C) med sm\xE4lt sm\xF6r"
    },
    {
      time: "00:05",
      action: "Tills\xE4tt mj\xF6l och surdeg",
      description: "Blanda mj\xF6l, surdeg och het v\xE4tskeblandning"
    },
    {
      time: "00:15",
      action: "Kn\xE5da till sl\xE4t deg",
      description: "Kn\xE5da till mjuk, elastisk deg"
    },
    {
      time: formatTime(bulkTime),
      action: "Dela och vila",
      description: "Dela till 8 bitar, forma bollar, vila under handduk"
    },
    {
      time: formatTime(bulkTime + proofTime),
      action: "Kavla och stek",
      description: "Kavla tunna, stek i torr panna 20-30 sek per sida"
    }
  ];
}
function generateCountrySourdoughTimeline(bulkTime, proofTime) {
  return [
    {
      time: "00:00",
      action: "Autolys",
      description: "Blanda mj\xF6l och vatten, vila 30-60 min"
    },
    {
      time: "01:00",
      action: "Tills\xE4tt surdeg och salt",
      description: "Arbeta in aktiv surdeg och salt"
    },
    {
      time: "01:30",
      action: "F\xF6rsta set vikningar",
      description: "Stretch & fold var 30:e minut, 4 set totalt"
    },
    {
      time: formatTime(bulkTime),
      action: "F\xF6rbollning",
      description: "Forma till boll, vila 20-30 min"
    },
    {
      time: formatTime(bulkTime + 0.5),
      action: "Slutformning",
      description: "Forma till limpa, l\xE4gg i banneton"
    },
    {
      time: formatTime(bulkTime + proofTime),
      action: "Gr\xE4dda",
      description: "Gr\xE4dda med \xE5nga 250\xB0C i 20 min, sedan 230\xB0C"
    }
  ];
}
function generateBaguetteTimeline(bulkTime, proofTime) {
  return [
    {
      time: "00:00",
      action: "Blanda grunddeg",
      description: "Mj\xF6l, vatten, salt, j\xE4st - blanda till j\xE4mn deg"
    },
    {
      time: "00:45",
      action: "F\xF6rsta vikningen",
      description: "Bokvikning i bunke, vila 45 min"
    },
    {
      time: "01:30",
      action: "Andra vikningen",
      description: "Upprepa vikning, vila 45 min"
    },
    {
      time: formatTime(bulkTime),
      action: "F\xF6rforma",
      description: "Dela degen, f\xF6rforma till korta stockar"
    },
    {
      time: formatTime(bulkTime + 0.5),
      action: "Slutforma baguetter",
      description: "Forma till l\xE5nga baguetter, l\xE4gg i dukkorg"
    },
    {
      time: formatTime(bulkTime + proofTime),
      action: "Sk\xE4r och gr\xE4dda",
      description: "G\xF6r snitt, gr\xE4dda med \xE5nga 240\xB0C"
    }
  ];
}
function generateGenericTimeline(bulkTime, proofTime, mixing, style) {
  const timeline = [];
  timeline.push({
    time: "00:00",
    action: "Blanda ingredienser",
    description: `Blanda mj\xF6l, vatten (${mixing === "hand" ? "f\xF6r hand" : "med maskin"})`
  });
  if (style.defaultParams.hydration_pct > 65 && style.defaultParams.sugar_pct < 5) {
    timeline.push({
      time: "00:30",
      action: "Autolys",
      description: "Vila degen 30 min f\xF6r glutenutveckling"
    });
  }
  timeline.push({
    time: style.defaultParams.hydration_pct > 65 ? "01:00" : "00:30",
    action: "Tills\xE4tt salt och j\xE4st",
    description: "Arbeta in salt och j\xE4st, b\xF6rja bulkj\xE4sning"
  });
  if (mixing === "hand" && style.defaultParams.hydration_pct > 65) {
    timeline.push({
      time: "01:30",
      action: "F\xF6rsta vikningen",
      description: "Coil fold eller stretch & fold"
    });
    timeline.push({
      time: "02:15",
      action: "Andra vikningen",
      description: "Coil fold eller stretch & fold"
    });
  }
  timeline.push({
    time: formatTime(bulkTime),
    action: style.category === "pizza" ? "Dela och bolla" : "Forma",
    description: style.category === "pizza" ? "Dela degen och forma bollar" : "Forma br\xF6d och l\xE4gg i korg/form"
  });
  timeline.push({
    time: formatTime(bulkTime + proofTime),
    action: "Klar att gr\xE4dda",
    description: style.category === "pizza" ? "Kavla ut och toppa pizza" : "Baka br\xF6det"
  });
  return timeline;
}
function formatTime(hours) {
  const h = Math.floor(hours);
  const m = Math.round(hours % 1 * 60);
  return h.toString().padStart(2, "0") + ":" + m.toString().padStart(2, "0");
}
function generateNotes(inputs, yeastPct, waterTemp, eff) {
  const notes = [];
  if (eff.rawWaterTemp !== waterTemp) {
    notes.push(`\u26A0\uFE0F Ber\xE4knad vattentemperatur (${eff.rawWaterTemp.toFixed(1)}\xB0C) ligger utanf\xF6r praktiskt intervall och har justerats till ${waterTemp.toFixed(1)}\xB0C.`);
  }
  if ((inputs.coldHours ?? 0) > inputs.totalTime) {
    notes.push(`\u26A0\uFE0F Kyltiden var l\xE4ngre \xE4n den totala tiden och har begr\xE4nsats till ${eff.coldHours}h.`);
  }
  if (waterTemp < 5) {
    notes.push("\u26A0\uFE0F Vattentemperaturen \xE4r mycket l\xE5g. \xD6verv\xE4g kortare j\xE4sningstid eller h\xF6gre rumstemperatur.");
  } else if (waterTemp > 50) {
    notes.push("\u26A0\uFE0F Vattentemperaturen \xE4r h\xF6g. Kontrollera att j\xE4sten inte d\xF6das (max 50\xB0C f\xF6r f\xE4rsk j\xE4st).");
  }
  if (eff.hydrationPct > 75) {
    notes.push("\u{1F4A1} H\xF6g hydrering: Anv\xE4nd v\xE5ta h\xE4nder vid vikning och var f\xF6rsiktig vid formning.");
  }
  if (inputs.leavenType !== "sourdough" && yeastPct > 0 && yeastPct < 0.02) {
    notes.push("\u26A0\uFE0F Mycket lite j\xE4st ber\xE4knat. Kontrollera j\xE4sningstid och temperatur.");
  }
  if (eff.oilPct > 10) {
    notes.push("\u{1F4A1} Fet deg: Tills\xE4tt fett efter glutenutveckling f\xF6r b\xE4sta resultat.");
  }
  switch (inputs.style.id) {
    case "neapolitan":
      notes.push("\u{1F355} Traditionell napolitansk: Vikning 3x med 15min vila. Bulkj\xE4sning 12-14h vid 21\xB0C.");
      notes.push("\u{1F355} Gr\xE4ddas vid 900\xB0C i 60-90 sekunder. Hemugn: 250\xB0C med bakst\xE5l, 8-12 min.");
      break;
    case "ny_style":
      notes.push("\u{1F355} Gr\xE4ddas vid 250\xB0C i 12-15 minuter. Anv\xE4nd bakst\xE5l f\xF6r b\xE4sta resultat.");
      break;
    case "pizza_poolish":
      notes.push("\u{1F355} Poolish dag 1: Blanda och j\xE4s 2h rumstemperatur, sedan 18-24h i kyl.");
      notes.push("\u{1F355} Dag 2: Kn\xE5da slutdeg, 2h rumstemperatur f\xF6re utbakning. M\xE5l: leopard spotting.");
      break;
    case "pizza_biga":
      notes.push("\u{1F355} Biga dag 1: Torr biga 18h vid 16\xB0C. Kr\xE4ver W300+ mj\xF6l f\xF6r styrka.");
      notes.push("\u{1F355} Dag 2: Kn\xE5da med isvatten + malt. Windowpane-test m\xE5ste klara. 3h bollning.");
      break;
    case "country_sourdough":
      notes.push("\u{1F35E} Gr\xE4ddas med \xE5nga f\xF6rsta 20 min, sedan utan lock. 230\xB0C \u2192 200\xB0C.");
      break;
    case "baguette":
      notes.push("\u{1F956} G\xF6r snitt precis f\xF6re gr\xE4ddning. \xC5nga f\xF6rsta 15 min.");
      break;
    case "milkbread":
      notes.push("\u{1F35E} Tangzhong-metod: Koka 30g mj\xF6l + 150ml mj\xF6lk/vatten till tjock konsistens.");
      notes.push("\u{1F35E} Tills\xE4tt 25g torrmj\xF6lkspulver f\xF6r extra mjukhet. Pensla med mj\xF6lk.");
      break;
    case "pain_de_mie_traditional":
      notes.push("\u{1F35E} Blanda j\xE4st i fingervarmt vatten. Kn\xE5da 10-15 min till sl\xE4t deg.");
      notes.push("\u{1F35E} Baka i lock till dubbel storlek vid 220\xB0C, s\xE4nk till 190\xB0C.");
      break;
    case "sourdough_form_bread":
      notes.push("\u{1F35E} Vikning i bunke flera g\xE5nger. 30 min vila mellan vikningar.");
      notes.push("\u{1F35E} Forma till avl\xE5ng limpa. 3-4h j\xE4sning vid rumstemperatur.");
      break;
    case "sourdough_tortillas":
      notes.push("\u{1F32E} MMS-metoden: Hett vatten + sm\xE4lt sm\xF6r = mjuka tortillas.");
      notes.push("\u{1F32E} Stek i torr panna 20-30 sek per sida tills de bubblar.");
      break;
  }
  return notes;
}

// src/lib/mcp/tools/calculate-recipe.ts
var calculate_recipe_default = defineTool3({
  name: "calculate_recipe",
  title: "Calculate dough recipe",
  description: "Calculate a full dough recipe for a style: ingredient weights in grams, baker's percentages, water temperature, bulk and proof times, timeline and notes.",
  inputSchema: {
    style_id: z3.string().min(1).describe("Style id, e.g. 'neapolitan' (see list_styles)."),
    ball_weight: z3.number().describe("Weight per dough ball/loaf in grams, e.g. 265."),
    ball_count: z3.number().int().describe("Number of dough balls/loaves, e.g. 8."),
    total_time: z3.number().describe("Total fermentation time in hours, e.g. 24."),
    room_temp: z3.number().describe("Room temperature in \xB0C, e.g. 23."),
    cold_hours: z3.number().optional().describe("Hours of cold fermentation at 4\xB0C. Default 0."),
    leaven_type: z3.enum(["commercial", "sourdough", "hybrid"]).optional().describe("Leavening type. Default 'commercial'."),
    yeast_form: z3.enum(["fresh", "active_dry", "instant"]).optional().describe("Yeast form. Default 'instant'."),
    mixing: z3.enum(["hand", "spiral", "planetary", "dlx"]).optional().describe("Mixing method. Default 'hand'."),
    desired_dough_temp: z3.number().optional().describe("Desired dough temperature in \xB0C. Default 24.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (input) => {
    const style = getStyleById(input.style_id);
    if (!style) throw new ToolError2(`Unknown style id: ${input.style_id}. Use list_styles to see valid ids.`);
    const results = calculateRecipe({
      style,
      ballWeight: input.ball_weight,
      ballCount: input.ball_count,
      totalTime: input.total_time,
      roomTemp: input.room_temp,
      coldTemp: 4,
      coldHours: input.cold_hours ?? 0,
      leavenType: input.leaven_type ?? "commercial",
      yeastForm: input.yeast_form ?? "instant",
      mixing: input.mixing ?? "hand",
      desiredDoughTemp: input.desired_dough_temp ?? 24
    });
    const payload = { style: { id: style.id, name: style.name }, ...results };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/explain-recipe.ts
import { defineTool as defineTool4, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z4 } from "npm:zod@^3.25.76";
var explain_recipe_default = defineTool4({
  name: "explain_recipe",
  title: "Explain dough recipe",
  description: "Calculate a recipe and return a human-friendly, plain-language explanation of it, including the 'why' behind every key correction: yeast scaling for time and temperature (Q10), salt/sugar/hydration corrections, cold-retard equivalence, DDT water temperature and the bulk/proof split.",
  inputSchema: {
    style_id: z4.string().min(1).describe("Style id, e.g. 'neapolitan' (see list_styles)."),
    ball_weight: z4.number().describe("Weight per dough ball/loaf in grams, e.g. 265."),
    ball_count: z4.number().int().describe("Number of dough balls/loaves, e.g. 8."),
    total_time: z4.number().describe("Total fermentation time in hours, e.g. 24."),
    room_temp: z4.number().describe("Room temperature in \xB0C, e.g. 23."),
    cold_hours: z4.number().optional().describe("Hours of cold fermentation at 4\xB0C. Default 0."),
    hydration: z4.number().optional().describe("Override hydration in baker's %, e.g. 65."),
    salt: z4.number().optional().describe("Override salt in baker's %, e.g. 2.5."),
    leaven_type: z4.enum(["commercial", "sourdough", "hybrid"]).optional().describe("Leavening type. Default 'commercial'."),
    yeast_form: z4.enum(["fresh", "active_dry", "instant"]).optional().describe("Yeast form. Default 'instant'."),
    mixing: z4.enum(["hand", "spiral", "planetary", "dlx"]).optional().describe("Mixing method. Default 'hand'."),
    desired_dough_temp: z4.number().optional().describe("Desired dough temperature in \xB0C. Default 24.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (input) => {
    const style = getStyleById(input.style_id);
    if (!style) throw new ToolError3(`Unknown style id: ${input.style_id}. Use list_styles to see valid ids.`);
    const roomTemp = input.room_temp;
    const leavenType = input.leaven_type ?? "commercial";
    const yeastForm = input.yeast_form ?? "instant";
    const mixing = input.mixing ?? "hand";
    const ddt = input.desired_dough_temp ?? 24;
    const r = calculateRecipe({
      style,
      ballWeight: input.ball_weight,
      ballCount: input.ball_count,
      totalTime: input.total_time,
      roomTemp,
      coldTemp: 4,
      coldHours: input.cold_hours ?? 0,
      hydration: input.hydration,
      salt: input.salt,
      leavenType,
      yeastForm,
      mixing,
      desiredDoughTemp: ddt
    });
    const p = r.params;
    const q10 = Math.pow(2.2, (roomTemp - 23) / 10);
    const friction = { hand: 2, spiral: 8, planetary: 6, dlx: 4 }[mixing];
    const sections = [];
    sections.push(
      `# ${style.name} \u2014 ${input.ball_count} \xD7 ${input.ball_weight} g (${p.totalDoughWeight} g dough)
${style.description} (${style.region}).`
    );
    sections.push(
      `## Ingredients
` + r.ingredients.map((i) => `- ${i.name}: ${i.grams < 10 ? i.grams.toFixed(2) : Math.round(i.grams)} g (${i.percentage}% of flour)`).join("\n") + `

Why: everything is expressed in baker's percentages against ${r.totalFlour} g of flour. The flour weight is derived by dividing the target dough weight by the sum of all percentages (100% flour + ${p.hydration}% water + ${p.salt}% salt` + (p.sugar ? ` + ${p.sugar}% sugar` : "") + (p.oil ? ` + ${p.oil}% fat` : "") + `), so the finished dough lands on the weight you asked for instead of overshooting it.`
    );
    const timeExplain = p.coldHours > 0 ? `You asked for ${p.totalTime} h total with ${p.coldHours} h in the fridge. Cold fermentation at 4 \xB0C runs at roughly 30% of room-temperature speed, so those ${p.coldHours} h count as about ${(p.coldHours * 0.3).toFixed(1)} h of activity. The dough therefore behaves like a ${p.roomEquivTime} h room-temperature ferment, and the yeast is dosed for that \u2014 not for the ${p.totalTime} h on the clock.` : `The whole ${p.totalTime} h runs at room temperature, so clock time and effective fermentation time are the same (${p.roomEquivTime} h).`;
    const yeastExplain = leavenType === "sourdough" ? `This is a sourdough build: ${p.inoculationPct}% inoculation (starter flour as a share of total flour). The starter's flour and water are subtracted from the main flour and water so the final hydration stays at ${p.hydration}%.` : leavenType === "hybrid" ? `Hybrid leavening: ${p.inoculationPct}% starter for flavour plus ${r.yeastPercentage}% ${yeastForm.replace("_", " ")} yeast for reliable lift. Both doses are halved versus their solo equivalents so the dough doesn't over-ferment.` : `Yeast: ${r.yeastPercentage}% ${yeastForm.replace("_", " ")} yeast.

Why that number \u2014 each correction in turn:
- Base dose: ${style.fermentation.base_yeast_fresh_pct || 0.3}% fresh yeast, the reference dose for this style over 24 h at 23 \xB0C.
- Time: the dose scales as 24 / ${p.roomEquivTime} h. Less time needs proportionally more yeast; a long ferment needs very little.
- Temperature (Q10 = 2.2): at ${roomTemp} \xB0C the dough ferments ${q10.toFixed(2)}\xD7 as fast as at 23 \xB0C, so the dose is divided by ${q10.toFixed(2)}. Every 10 \xB0C roughly doubles yeast activity.
- Salt at ${p.salt}%: salt draws water out of yeast cells and slows them, so above 2% the dose is nudged up (and below 2%, down).
` + (p.sugar ? `- Sugar at ${p.sugar}%: sugar feeds the yeast at low levels but at high levels its osmotic pressure stresses them, so the dose is raised slightly.
` : "") + `- Hydration at ${p.hydration}%: a wetter dough is more mobile and ferments faster, so wetter doughs get slightly less yeast.
` + (yeastForm !== "fresh" ? `- Form conversion: fresh yeast \u2192 ${yeastForm.replace("_", " ")} using ${yeastForm === "instant" ? "\xD70.33" : "\xD70.40"}, because dried yeast is far more concentrated.
` : "") + `All corrections are clamped, so extreme inputs can never produce a negative or absurd dose.`;
    sections.push(`## Fermentation
${timeExplain}

${yeastExplain}`);
    sections.push(
      `## Water temperature \u2014 ${r.waterTemp} \xB0C
Desired dough temperature is ${ddt} \xB0C. Using the standard DDT rule for a three-factor dough: water = 3 \xD7 ${ddt} \u2212 flour temp (${roomTemp} \xB0C) \u2212 room temp (${roomTemp} \xB0C) \u2212 friction (${friction} \xB0C for ${mixing} mixing).

Why: mixing itself heats the dough, and the more powerful the mixer the more it adds (${mixing} \u2248 ${friction} \xB0C). Water is the only ingredient you can easily temper, so it absorbs the whole correction. Hitting the dough temperature matters more than the clock \u2014 a dough 2 \xB0C warmer ferments roughly 15% faster.`
    );
    sections.push(
      `## Bulk and proof \u2014 ${r.bulkTime} h bulk, ${r.proofTime} h final proof
The ${p.totalTime} h are split using this style's ratio (${style.fermentation.bulk_ratio} bulk / ${style.fermentation.proof_ratio} proof, normalised to sum to 1). Why: bulk fermentation builds flavour and strength while the dough is one mass; the final proof after shaping only needs enough time to relax and inflate the shaped piece. ${style.category === "pizza" ? "Pizza styles are bulk-heavy so the balls stay easy to open." : "Loaf styles keep a longer final proof so the shaped piece can fully expand."}`
    );
    if (r.notes.length) sections.push(`## Notes
${r.notes.map((n) => `- ${n}`).join("\n")}`);
    sections.push(`## Timeline
${r.timeline.map((t) => `- ${t.time} \u2014 ${t.action}: ${t.description}`).join("\n")}`);
    const explanation = sections.join("\n\n");
    return {
      content: [{ type: "text", text: explanation }],
      structuredContent: { style: { id: style.id, name: style.name }, explanation, recipe: r }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "dough-designer-pro",
  title: "dough-designer-pro",
  version: "0.1.0",
  instructions: "Tools for the Baker's Calculator. Use `list_styles` to browse bread and pizza styles, `get_style` for a style's default parameters, `calculate_recipe` to compute ingredient weights, water temperature, fermentation times and a baking timeline, and `explain_recipe` for a plain-language walkthrough of the same recipe including the reasoning behind each correction.",
  tools: [list_styles_default, get_style_default, calculate_recipe_default, explain_recipe_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.3/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
